### ISSUE TITLE
"uses Modernizer" prevent to compile Bcrypt.pas

### ISSUE THREAD

**Issue by Anasthase** [marcelocantos/bcrypt-for-delphi#2]
With commit 2561ebdb7ad6634b86faecf74ffc5bfa79d86e02 came "Modernizer" in uses of BCrypt.pas. This prevent me from compiling. Removing it allow to compile.

What is the purpose of "Modernizer", and is it safe to remove it?

Thanks in advance.

**Comment by marcelocantos** [comment]
I haven't used Delphi for a while now and have neither the ability to compile/run this code nor plans to do so in the foreseeable future. I will probably delete this repo soon, so please feel free to fork and fix.

**Comment by JoseJimeniz** [comment]
I fixed it in my fork. I originally wrote the it; but marcelocantos added it to GitHub. So he's the mainline. i've been putting changes in my fork - occasionally harassing him to pull.

**Comment by Anasthase** [comment]
I'll head to your fork then JoseJimeniz. Thanks both of you for your feedback.
